### ISSUE TITLE
Daily Expense Reminder

### ISSUE THREAD

**Issue by nikki1234567** [ShanmukhaSreenivas/DollarBot#7]
A scheduling feature that sends users a reminder to log their daily expenses if none have been recorded. This ensures users maintain a consistent habit of tracking their expenses and stay on top of their financial activities.

**Comment by ShanmukhaSreenivas** [comment]
Implemented and fixed the daily expense reminder feature in multiple commits

Commit ID : 42384264daa1dba318582f73503ff69bb1725f19, fc5a4d9629e7bdd6328ca8c65bb4bf88834ccd69
